# action.yml
name: "Rust Cargo Deb Package Build (amd64, Ubuntu)"
description: "Builds a statically linked .deb package, amd64, musl, ubuntu"
branding:
  icon: "package"
  color: "orange"
inputs:
  cmd:
    description: "build command"
    required: true
    default: "cargo deb --target=x86_64-unknown-linux-musl"
runs:
  using: "docker"
  image: "docker://ghcr.io/wouterdebie/cargo-deb-amd64-ubuntu:1.2"
  args:
    - ${{ inputs.cmd }}
